Classes/ContentObject/JsonContentObject.php

Simplify condition in JSON Content object, handle also missing case with float or boolean condition.

Change conditions in Json content object to prevent errors with strict types

---

Configuration/TypoScript/ContentElement/Default.typoscript

When a rendering definition (TypoScript) is missing for a content element (e.g when TypoScript is not included or incorrect) the output of the "content" is as follows:
```json
"colPos": [
null,
null
],
```
This makes it harder to track down the problem. When overriding `tt_content.default` and adding the error output to the JSON, debugging is much easier. :)
New output inside the correct colPos array is:
```json
{
"appearance": {
"frameClass": "default",
"layout": "default",
"spaceAfter": "",
"spaceBefore": ""
},
"colPos": 0,
"content": "ERROR: Content Element with uid \"3\" and type \"tx_myextension_contentelement\" has no rendering definition!",
"id": 3,
"pid": 1,
"type": "tx_myextension_contentelement"
}
```
besr,
R

[FEATURE] Output error for missing rendering definition in JSON

---

Classes/DataProcessing/FilesProcessor.php
Configuration/TypoScript/ContentElement/Image.typoscript
Configuration/TypoScript/ContentElement/MenuAbstract.typoscript
Configuration/TypoScript/ContentElement/MenuCategorizedContent.typoscript
Configuration/TypoScript/ContentElement/MenuCategorizedPages.typoscript
Configuration/TypoScript/ContentElement/MenuRecentlyUpdated.typoscript
Configuration/TypoScript/ContentElement/MenuRelatedPages.typoscript
Configuration/TypoScript/ContentElement/MenuSectionPages.typoscript
Configuration/TypoScript/ContentElement/MenuSitemap.typoscript
Configuration/TypoScript/ContentElement/MenuSitemapPages.typoscript
Configuration/TypoScript/ContentElement/Textmedia.typoscript
Configuration/TypoScript/ContentElement/Textpic.typoscript
Configuration/TypoScript/ContentElement/Uploads.typoscript

Change ImagesProcessor to FilesProcessor, output data directly, without additional nesting level
Rename DataProcessor, change to all files using ImageProcessor. Remove additional array 'images' to provide clean output.

[TASK]  Change ImagesProcessor to FilesProcessor, output data directly, without additional nesting level

---

Classes/DataProcessing/GalleryProcessor.php

Images in this function was processing before. 
In TYPO3 v10 was also error because getImage() need string but int is given

[BUGFIX] Remove double image processing

---

Classes/Utility/ContentUtility.php

Hi @tmotyl,
hi @lukaszuznanski ,
a content element with negative colpos value should be ignored in the json output (e.g when using gridelements).
Feel free to ask any further questions :)
best,
R. Schlosser

[BUGFIX] Ignore negative colpos values

---

Classes/Utility/FileUtility.php

There is bug which occurs when we crop images. Images are cropped, but then resized to original size, so at the end, image is wrongly processed.

[BUGFIX] Crop images without resizing

---

Classes/DataProcessing/FilesProcessor.php
Classes/Utility/FileUtility.php

I had the challenge to make use of cropVariants defined in every Image Element. So I found that headless sets it to "default" and there was no option to get it respected.

Make cropVariant configurable through processingConfiguration in FilesProcessor

---

Classes/Form/CustomOptionsInterface.php
Classes/Form/Decorator/AbstractFormDefinitionDecorator.php
Classes/Form/Decorator/DefinitionDecoratorInterface.php
Classes/Form/Decorator/FormDefinitionDecorator.php
Classes/Form/Finisher/JsonRedirectFinisher.php
Classes/Form/Service/FormTranslationService.php
Classes/Form/Translator.php
Classes/XClass/Controller/FormFrontendController.php
Classes/XClass/FormRuntime.php
Configuration/TypoScript/Configuration/Form.typoscript
Configuration/TypoScript/ContentElement/Form.typoscript
Resources/Private/Form/Templates/Form.html
Resources/Private/Form/Templates/Render.html
ext_localconf.php

Resolves #79 and:
- add support of core translation of form labels etc (translated same way as fluid form)
- pagination of form (pages/tabs)
- support of custom options (i.e. from database) in selects
- add custom finisher for redirect for headless API
- add form response decorator and API to customize per project

[FEATURE] add initial support for ext: form

---

Classes/XClass/Controller/FormFrontendController.php

before handle forms in headless' way. if not call
original method for fluid's based forms.
Resolves #218 where we have headless & fluid based sites in same instance.

[FIX] check if headless configuration is loaded in current site

---

Classes/DataProcessing/RootSiteProcessing/DomainSchema.php
Classes/DataProcessing/RootSiteProcessing/SiteProvider.php
Classes/DataProcessing/RootSiteProcessing/SiteProviderInterface.php
Classes/DataProcessing/RootSiteProcessing/SiteSchema.php
Classes/DataProcessing/RootSiteProcessing/SiteSchemaInterface.php
Classes/DataProcessing/RootSiteProcessing/SiteSortingInterface.php
Classes/DataProcessing/RootSitesProcessor.php
Configuration/TypoScript/Configuration/Domains.typoscript

- add default SiteProvider (combines data from yaml files & database) with optional custom sorting
- add default SiteSchema (outputs domain list for site switcher)
- add default DomainSchema (outputs domain configuration for nuxt-typo3 app)
All providers & schemas are switchable by implementing proper interface
and configure it in data processor options

[FEATURE] introduce RootSiteProcessor

---

Classes/XClass/ImageService.php
ext_localconf.php

When processing files via PWA file proxy, ImageService receives bad file src path and do not find file in storage then crash with exception.

[BUGFIX] cleanup filepath from file proxy setting

---

Classes/Event/Listener/RedirectUrlAdditionalParamsListener.php
Classes/Event/RedirectUrlEvent.php
Classes/Middleware/RedirectHandler.php
Configuration/RequestMiddlewares.php

- behind `headless.redirectMiddlewares` flag & `headless` flag in site config
- replace original redirectHandler with headless one
- introduce RedirectUrlEvent for EventDispatcher/hook for TYPO3 v9.5 to allow customizations of redirect url without replacing middleware
- introduce optional listener for handling additionalParams in redirect url
- add support for `headless.storageProxy` in file redirection

[TASK] introduce support ext:redirect for nuxt-typo3

---

Documentation/Developer/Index.rst

I was having a hard time figuring our how to render `CONTENT` objects without having to use a userFunc. That's why I think the documentation needs to have a section on that topic.

Add section about rendering default TypoScript objects

---

Classes/Seo/XmlSitemap/XmlSitemapRenderer.php

- use in Typoscript `plugin.tx_seo.config.overrideFrontendBaseKey` = `new_key_from_site_configuration`
- supports base variants

[FEATURE] add ability to override frontendBase in sitemap generator

---

Classes/Middleware/PluginBodyResponseMiddleware.php
Configuration/RequestMiddlewares.php
README.md

- add new `headless.pluginBodyResponse` feature flag (off by default)
- requires sending `responsePluginId` with plugin data to receive clean output
- works only for POST/PUT/DELETE requests
resolves #191

[FEATURE] add support for clean output for plugins

---

ext_emconf.php

With TYPO3 11.5 and PHP 8.0 there was a critical error with DI while using headless extension.

[TASK] Fix configuration

---

Classes/ContentObject/JsonContentObject.php
Classes/DataProcessing/RootSiteProcessing/DomainSchema.php
Classes/DataProcessing/RootSiteProcessing/SiteProvider.php
Classes/DataProcessing/RootSiteProcessing/SiteSchema.php
Classes/DataProcessing/RootSitesProcessor.php
Classes/Dto/JsonViewDemand.php
Classes/Form/Decorator/FormDefinitionDecorator.php
Classes/Form/Translator.php
Classes/Json/JsonDecoder.php
Classes/Json/JsonEncoder.php
Classes/Middleware/ElementBodyResponseMiddleware.php
Classes/Middleware/RedirectHandler.php
Classes/Middleware/ShortcutAndMountPointRedirect.php
Classes/Service/BackendTsfeService.php
Classes/Service/JsonViewConfigurationService.php
Classes/Utility/UrlUtility.php

Related to https://github.com/TYPO3-Initiatives/headless/issues/381 I dropped the final keywords to increase the expendability of the extension.

[TASK] Drop final class annotations to support all TYPO3s expendability options

---

Classes/Hooks/FileOrFolderLinkBuilder.php
ext_localconf.php

Currently URLs generated for typolink files (for instance, in RTE
content elements) are being rendered as relative links. This commit
changes them to be rendered as absolute, because relative URLs don't
work when loading images from an external domain.

[BUGFIX][BACKPORT] Render typolink file URLs as absolute

---

Classes/DataProcessing/DatabaseQueryProcessor.php
Classes/DataProcessing/FlexFormProcessor.php

Added the possibility to process data, which is in $processedData[$fieldName] instead of $processedData['data'][$fieldName]. 
We needed this to process flexform data in a result of the DatabaseQueryProcessor.
This makes it possible, to configure only one field of the result.
We have a link field, which wasn't parsed as typolink. But we didn't want to define every single field of the query. So we added the key "overrideFields".
e.g.:
```
20 = FriendsOfTYPO3Headless\HeadlessBootstrapPackage\DataProcessing\DatabaseQueryProcessor
20 {
table = tx_bootstrappackage_carousel_item
pidInList.field = pid
where {
data = field:uid
intval = 1
wrap = tt_content=|
}
overrideFields {
link = TEXT
link {
field = link
htmlSpecialChars = 1
typolink {
parameter {
field = link
}
returnLast = result
}
}
} …
```

Extended Dataprocessors

---

Classes/DataProcessing/FilesProcessor.php

The FilesProcessor just outputs the URL to one given cropVariant (or "default") plus the crop-config array stored in $image['properties']['crop']. 
This data isn't all that useful for a frontend application though.
This PR adds a "cropVariants" Key to the processed image data, containing all rendered and processed cropVariants of a given File.
This way a frontend app can access the cropped images very easily.
Example Output:

FilesProcessor: Added processed cropVariants to JSON output

---

Classes/Service/Parser/PageJsonParser.php

In the JsonView module `undefined key "page" warning` is thrown.

[FIX] Add fallback for undefined key "page" warning in php8

---

Classes/DataProcessing/DatabaseQueryProcessor.php
Documentation/Developer/Index.rst

In order for this meta data override to work we had to introduce a new flag `renderOnlyOne` to `DatabaseQueryProcessor`.
Maybe there's a better solution?
```
lib.meta.stdWrap.override.cObject = JSON
lib.meta.stdWrap.override.cObject {
stdWrap.if.isTrue.data = GP:tx_news_pi1|news
dataProcessing.10 = FriendsOfTYPO3\Headless\DataProcessing\DatabaseQueryProcessor
dataProcessing.10 {
table = tx_news_domain_model_news
uidInList.data = GP:tx_news_pi1|news
uidInList.intval = 1
pidInList = 0
max = 1
as = records
fields < lib.meta.fields
fields {
title = TEXT
title.field = title
subtitle = TEXT
subtitle.field = teaser
description = TEXT
description.field = bodytext
}
renderOnlyOne = 1
}
}
```
| Before | After |
| -- | -- |
| ![Bildschirmfoto vom 2022-03-18 …

[FEATURE] Add flag to DatabaseQueryProcessor to render only one record

---

Classes/Middleware/ShortcutAndMountPointRedirect.php

This middleware replaces original core middleware to pass handling of shortcut redirect to the frontend app via Json Response, this PR fixes issue with multi-site installation, old way of checking for enabled headless does not work correctly when one instance has more than one site configured.

[BUGFIX] add support for multi-site installations

---

Classes/ContentObject/JsonContentContentObject.php

The method "getFrontendController" was removed from ContentContentObject.php in TYPO3 11.5.14

Use getTypoScriptFrontendController

---

Classes/DataProcessing/RootSiteProcessing/SiteProvider.php
Classes/Form/Translator.php
Classes/Service/PaginationService.php
Classes/ViewHelpers/Form/RegisterFieldViewHelper.php
Classes/ViewHelpers/Format/Json/DecodeViewHelper.php
Classes/ViewHelpers/LoginFormViewHelper.php
Classes/XClass/Controller/FormFrontendController.php
Classes/XClass/ResourceLocalDriver.php
Configuration/RequestMiddlewares.php
Configuration/Services.php
Configuration/SiteConfiguration/Overrides/site.php
Configuration/SiteConfiguration/Overrides/site_base_variant.php
Configuration/TCA/Overrides/sys_template.php
Tests/Functional/ContentTypes/DefaultContentsTest.php
ext_emconf.php
ext_localconf.php
ext_tables.php

- migrate TYPO3_MODE constants resolve #490
- simplify namespace importing in TYPO3 v11

[TASK] apply v11 improvements & remove deprecations

---

Classes/ContentObject/JsonContentContentObject.php

fixes edge case when rendering element(s) cause render incorrect colpos with null values

[BUGFIX] Fix rendering broken colpos

---

ext_localconf.php

Without this line the CE definitions are missing when using the 2.x output.

Also add 2.x CEs in `contentRenderingTemplates`

---

Classes/Utility/FileUtility.php
Tests/Unit/Utility/FileUtilityTest.php

Typolink method return empty string when it can not resolve link parameter

[BUGFIX] Fix crash when link is not resolved properly

---

Classes/DataProcessing/FilesProcessor.php

stdWrap functionality is missing in FilesProcessor. With this change it is possible, for example, to get files from custom fields with slide.
Example (not working without patch)
```
page {
10 {
fields {
heroimage = TEXT
heroimage {
dataProcessing {
10 = FriendsOfTYPO3\Headless\DataProcessing\FilesProcessor
10 {
as = heroimage
references.data = levelfield: -1, heroimage, slide
}
}
}
}
}
}
```

Add stdWrap functionality to FilesProcessor

---

Classes/Middleware/ElementBodyResponseMiddleware.php
Tests/Unit/Middleware/ElementBodyResponseMiddlewareTest.php

Fixed the possibility to get elementBodyResponse also if doNotGroupByColPos = 1 is set on lib.content

elementBodyResponse in combination with doNotGroupByColPos = 1

---

Resources/Private/FeLogin/Partials/FlashMessages.html

With `[BE][debug] = true ` the FlashMessages partial in FeLogin will lead to an error in the DecodeViewHelper if there are no flashMessages because the FlashMessagesViewhelper will return an empty string.

[BUGFIX] Fix fe-login flashMessages partial with fe debug enabled

---

Classes/Form/Translator.php
Classes/XClass/Controller/FormFrontendController.php
Tests/Unit/Form/TranslatorTest.php

[BUGFIX/FEATURE] Submitted form should return sent data to the frontend

---

Classes/Utility/FileUtility.php
Tests/Unit/Utility/FileUtilityTest.php

[TASK] Cleanup FileUtility

---

Classes/XClass/TemplateView.php
Configuration/Services.php
Tests/Unit/XClass/Fixtures/Templates/Default/Default.php
Tests/Unit/XClass/TemplateViewTest.php

resolves: #184
Feature if enabled replaces rendering templates in fluid in frontend context with php templates in order to simplify output json.
Templates paths resolving is the same as in fluid, feature seeks just files with php extension,
In php template you should just echo json_encode([...]);
How to enable:
- add new `headless.overrideFluidTemplates` flag to LocalConfiguration
- add to typoscript settings for desired plugin, flag `phpTemplate`=1 in order to override fluid templates

[FEATURE][PoC] Introduce way to skip fluid templates

---

Classes/DataProcessing/FlexFormProcessor.php

Configure individual fields of the FlexFormProcessor result. Same as overrideFields in DatabaseQueryProcessor, but for FlexFormProcessor (see also: https://github.com/TYPO3-Headless/headless/pull/407/commits/bf8da4789a91f1089e3ae411edec35eeb7258239). Allows to convert typolinks, images, ...
```
10 = FriendsOfTYPO3\Headless\DataProcessing\FlexFormProcessor
10 {
fieldName = pi_flexform
as = flexform
overrideFields {
image = TEXT
image {
dataProcessing {
10 = FriendsOfTYPO3\Headless\DataProcessing\FilesProcessor
10 {
references {
table = tt_content
fieldName = image
}
as = image
}
}
}
link = TEXT
link {
field = link
htmlSpecialChars = 1
typolink {
parameter {
field = link
}
returnLast = result
}
}
}
}
```
```json
{
"flexform": {
"image": "1",
"link": "t3:\/\/page?uid=13"
}
}
```
```json
{ …
```

Add overrideFields to FlexFormProcessor

---

Configuration/Services.php
Tests/Functional/ContentTypes/MenuAbstractPagesElementTest.php
Tests/Functional/ContentTypes/MenuCategorizedPagesElementTest.php
Tests/Functional/ContentTypes/MenuPagesElementTest.php
Tests/Functional/ContentTypes/MenuRecentlyUpdatedPagesElementTest.php
Tests/Functional/ContentTypes/MenuRelatedPagesElementTest.php
Tests/Functional/ContentTypes/MenuSectionElementTest.php
Tests/Functional/ContentTypes/MenuSitemapElementTest.php
Tests/Functional/ContentTypes/MenuSitemapSelectedPagesElementTest.php
Tests/Functional/ContentTypes/MenuSubpagesElementTest.php

- [BUGFIX] Properly configure headless ContentObjects/DataProcessors
- [FEATURE] Allow to use tagged alis for processor i.e. "headless-menu" instead of full class name
- Restored functional tests

v12 fixes part3

---

Classes/ContentObject/JsonContentContentObject.php
Classes/ContentObject/JsonContentObject.php
Classes/Utility/HeadlessUserInt.php
Tests/Unit/Hooks/HeadlessUserIntTest.php

Handles cases when plugin marked as USER_INT wants to in some case do not return some data, by default instead of empty string, we want set null for better type system in FE app

[FEATURE] Allow non cachable plugins to return null on empty

---

Classes/DataProcessing/GalleryProcessor.php
Configuration/SiteConfiguration/Overrides/site.php
Configuration/SiteConfiguration/Overrides/site_base_variant.php
Resources/Private/Language/locallang_siteconfiguration.xlf

This changes moves the hardcoded labels into a xlf file (in this case for labels inside "./Configuration/SiteConfiguration/"):
- Add xlf file for translating the site configuration
- Replace hardcoded labels with the labels from the translation file
Related: #545
Resolves: #545

[FEATURE] Move hardcoded labels to xlf files to support translation via crowdin (#545)

---

Classes/ViewHelpers/Format/Json/DecodeViewHelper.php
Tests/Unit/ViewHelpers/Format/Json/DecodeViewHelperTest.php

Adding trim() fixed the error when there was a space in the passed value along with one of the characters: \n \r \t \v \x00

[BUGFIX] Trim whitespaces in JSON decode helper

---

Classes/Utility/FileUtility.php

Fixes the following alert:
```
[ALERT] request="b5fa28bd5dc9b" component="TYPO3.CMS.Frontend.ContentObject.Exception.ProductionExceptionHandler": Oops, an error occurred! Code: 20230620052916f6fe734f- Exception: PHP Runtime Deprecation Notice: Creation of dynamic property FriendsOfTYPO3\Headless\Utility\FileUtility::$features is deprecated in /var/www/html/vendor/friendsoftypo3/headless/Classes/Utility/FileUtility.php line 60
```

[BUGFIX] Fix missing property in FileUtility

---

Classes/Utility/UrlUtility.php
Tests/Unit/Utility/UrlUtilityTest.php

[TASK] Normalize urls in all cases in order to avoid double slashes

---

Tests/Unit/ContentObject/JsonContentObjectTest.php
Tests/Unit/DataProcessing/RootSitesProcessorTest.php

FIX: Deprecated: Do not provide $request as third argument to start(). Call setRequest() before, instead.
Found this while working on #626

FIX: Deprecated: Do not provide $request as third argument

---

Classes/Middleware/SiteBaseRedirectResolver.php
Configuration/RequestMiddlewares.php
Tests/Unit/Middleware/SiteBaseRedirectResolverTest.php

Replace default SiteBaseRedirectResolver
with headless' one in order to handle proper redirects with headless approach.
- fix tests
- fix CS

[TASK] Improve redirect handling

---

Configuration/TypoScript/Page/Categories.typoscript

I think the key is wrong. 
In the PageConfiguration.typoscript file, there is a reference to lib.categories, but it does not exist.

[BUGFIX] Set correct typoscript key for categories

---

Configuration/TypoScript/Configuration/Domains.typoscript
Configuration/TypoScript/Configuration/InitialDataConfiguration.typoscript
Configuration/TypoScript/Configuration/PageConfiguration.typoscript
Configuration/TypoScript/Page/HeadlessPage.typoscript

This way we reduce code duplications and make it easier to add new headless pages (typeNums).

[FEATURE] Use shared TypoScript lib for headless pages

---

Classes/Event/Listener/AfterCacheableContentIsGeneratedListener.php
Configuration/Services.php
Tests/Unit/Event/Listener/AfterCacheableContentIsGeneratedListenerTest.php

Introduce listener to modify `meta.title` property on page render via call to `TSFE->generatePageTitle` with allows to get processed page title and/or set via extbase plugins
Resolves #543

[FEATURE] PageTitle handler for headless

---

Classes/ContentObject/JsonContentObject.php

This TypoScript option works similar to "ifEmptyReturnNull", however, the option uses the unset() feature to actually remove the key from the json output instead of setting this to null.
The code checks for "" and an explicit "false" (bool) when using the cObject = BOOL
Fixes: #649

[FEATURE] Add option "ifEmptyUnsetKey" to JSON cObject

---

Configuration/TypoScript/ContentElement/ContentElementWithHeader.typoscript
Tests/Functional/ContentTypes/BaseContentTypeTest.php
Tests/Functional/ContentTypes/BasicListElementTest.php
Tests/Functional/ContentTypes/BulletsElementTest.php
Tests/Functional/ContentTypes/HeaderElementTest.php
Tests/Functional/ContentTypes/ShortcutElementTest.php
Tests/Functional/ContentTypes/TableElementTest.php
Tests/Functional/ContentTypes/TextElementTest.php

Due to the additional option `field = header_link` setting the output of `linkText` value was always something like `t3://page?uid=13` for internal links. But it would be better to let typolink always handle the `linkText` to have it replaced with e.g the page title.
Current:
```json
"headerLink": {
"href": "/my-page",
"target": null,
"class": null,
"title": null,
"linkText": "t3://page?uid=13",
"additionalAttributes": []
}
```
Fixed:
```json
"headerLink": {
"href": "/my-page",
"target": null,
"class": null,
"title": null,
"linkText": "My Page",
"additionalAttributes": []
}
```

[BUGFIX] Correct `linkText` value in headerLink property

---

Classes/DataProcessing/GalleryProcessor.php

This adds a new option to GalleryProcessor to render a certain image format.
```
10 = FriendsOfTYPO3\Headless\DataProcessing\FilesProcessor
10 {
processingConfiguration.delayProcessing = 1
}
20 = FriendsOfTYPO3\Headless\DataProcessing\GalleryProcessor
20 {
fileExtension = webp
}
```
Related: #617

Add option for GalleryProcessor: fileExtension

---

Configuration/Services.php
Documentation/Configuration/Index.rst

[TASK] Set feature behind a flag

---

Classes/Event/Listener/AfterLinkIsGeneratedListener.php
Classes/Utility/UrlUtility.php
Tests/Unit/Event/Listener/AfterLinkIsGeneratedListenerTest.php
Tests/Unit/Utility/UrlUtilityTest.php

- Properly generate link to sitemap if sitemap request is not pass through proxy

[BUGFIX] Fix generating links to sitemap

---

Classes/ContentObject/JsonContentContentObject.php

When fetching non CE records via CONTENT_JSON we should not check for colPos, there is none.

[BUGFIX] Improve check for empty elements

---

Classes/DataProcessing/DataProcessingTrait.php

I tried using the simplified file output with `legacyReturn = 0` but in addition with `linkResult = 1` this leads to an error in the `removeDataIfnotAppendInConfiguration` function.

[BUGFIX] Fix linkResult configuration in simplified file output

---

Classes/Event/Listener/AfterLinkIsGeneratedListener.php
Tests/Unit/Event/Listener/AfterLinkIsGeneratedListenerTest.php

[BUGFIX] Properly decode cross domain links

---

Classes/Event/Listener/AfterCacheableContentIsGeneratedListener.php
Classes/Seo/CanonicalGenerator.php
Classes/Seo/MetaTag/AbstractMetaTagManager.php
Classes/Seo/MetaTag/EdgeMetaTagManager.php
Classes/Seo/MetaTag/Html5MetaTagManager.php
Classes/Seo/MetaTag/OpenGraphMetaTagManager.php
Classes/Seo/MetaTag/TwitterCardMetaTagManager.php
Configuration/Services.php
Configuration/TypoScript/Configuration/PageConfiguration.typoscript
Configuration/TypoScript/Page/Meta.typoscript
Tests/Unit/Event/Listener/AfterCacheableContentIsGeneratedListenerTest.php
Tests/Unit/Seo/MetaTag/MetaTagTest.php
ext_localconf.php

Patch introduces proper support of SEO related settings & APIs from TYPO3 core:
Patch adds ability to use:
- Canonical API
- MetaTag API
- Page title API
Respects `page.meta` TypoScript definitions.

[FEATURE] Introduce support of SEO related APIs from TYPO3 Core

---

Documentation/Configuration/Index.rst

- add to docs different approaches for content element categories configuration
- note that pidInList = root with recursive = 99 doesn't work

[TASK] Describe different approaches for handling of content element

---

Classes/Event/Listener/AfterPagePreviewUriGeneratedListener.php

InvalidArgumentException: Language -1 does not exist on site xyz

[BUGFIX] Exception in list module for CEs with language -1

---

Classes/DataProcessing/RootSiteProcessing/SiteProvider.php

- there was an error in line 99 before this change about illegal array offset because fetches returned empty array instead of results

[TASK] Fix SiteProvider fetch methods

---

Classes/XClass/Controller/FormFrontendController.php

This will render form validation errors with arguments, replacing placeholders with arguments if necessary (e.g. `The date "123" was not recognized (for format "Y-m-d\TH:i:sP").` for `The date "%s" was not recognized (for format "%s").`).

Render form validation errors with arguments

---

Classes/XClass/ResourceLocalDriver.php

Without a frontendApiProxy in the site config, URLs to local files contain two slashes like www.mysite.org//fileadmin/my-image.jpg

[BUGFIX] Don't render double slashes in file URLs

---

Classes/Frontend/BackendEditorUrl.php
Configuration/Services.php
Configuration/TypoScript/Configuration/BackendEditor.typoscript
Configuration/TypoScript/LoggedUser/BackendEditor.typoscript
Configuration/TypoScript/Mixed/setup.typoscript
Configuration/TypoScript/setup.typoscript

This patch prepares backend for nuxt-typo3 implementation.

[FEATURE] Add links for backend editor on the frontend

---

Classes/ViewHelpers/LoginFormViewHelper.php

[BUGFIX] Generate proper hash for v13 in LoginFormViewHelper

---

Configuration/RequestMiddlewares.php

Enabling the headless.redirectMiddlewares feature leads to an error if EXT:redirects is not installed although the feature can be used for exeample only shortcuts as well.

[BUGFIX] Allow headless.redirectMiddlewares feature without EXT:redirects
