TYPO3-Headless/headless

Configuration/TypoScript/Helper/DoktypeName.typoscript

There was something missing to get the correct doktypeName :)
best,
R

[BUGFIX] Add correct doktype field to lib.doktypeName

---

Classes/Service/PaginationService.php

Add PaginationService to allow ExtBase implementation of pagination of QueryResults.
Based on PaginateController which is used in PaginateViewHelper

[FEATURE] Add PaginationService

---

Configuration/TypoScript/ContentElement/Image.typoscript

This change fix gallery output in images content element.

[BUGFIX] Fix gallery output in images CE

---

Configuration/TypoScript/ContentElement/Table.typoscript
Configuration/TypoScript/Helper/ContentElement.typoscript
Configuration/TypoScript/Helper/Page.typoscript

Credits to @ChrisB9 for providing social media and nosearch fields

[TASK] Add missing fields to json output

---

Classes/DataProcessing/FilesProcessor.php
Classes/DataProcessing/GalleryProcessor.php
Configuration/TypoScript/ContentElement/Image.typoscript
Configuration/TypoScript/ContentElement/MenuAbstract.typoscript
Configuration/TypoScript/ContentElement/MenuCategorizedContent.typoscript
Configuration/TypoScript/ContentElement/MenuCategorizedPages.typoscript
Configuration/TypoScript/ContentElement/MenuRecentlyUpdated.typoscript
Configuration/TypoScript/ContentElement/MenuRelatedPages.typoscript
Configuration/TypoScript/ContentElement/MenuSection.typoscript
Configuration/TypoScript/ContentElement/MenuSectionPages.typoscript
Configuration/TypoScript/ContentElement/MenuSitemap.typoscript
Configuration/TypoScript/ContentElement/MenuSitemapPages.typoscript
Configuration/TypoScript/ContentElement/Textmedia.typoscript
Configuration/TypoScript/ContentElement/Textpic.typoscript
Configuration/TypoScript/ContentElement/Uploads.typoscript
Configuration/TypoScript/Helper/Page.typoscript

Provide way to output images and gallery data, process images, get rid of not needed nesting, output also youtube, vimeo data, unify naming conventions

[TASK] Unify dataprocessors, get rid of chaining dataprocessors

---

Classes/Utility/ImageUtility.php

This utility allows us to process images in PHP code, just like ImageViewHelper

[FEATURE] Add ImageUtility to process images in extbase

---

Classes/Utility/FileUtility.php

Added conditions to get properties from FAL

[BUGFIX] File props empty

---

.php_cs.dist

Follow up to https://github.com/TYPO3-Initiatives/headless/pull/56.

Added missing PSR-12 rule

---

Classes/Utility/FileUtility.php

Do not process svg files and code fixes

[BUGFIX] do not process svg files

---

Classes/DataProcessing/FilesProcessor.php

New (optional) feature flag allows to set option to remove "data" array from final output

[FEATURE] add "removeData" option to FilesProcessor

---

README.md

[BUGFIX] Add github actions badge

---

.github/workflows/ci.yaml

[TASK] Release to ter via github actions

---

Classes/DataProcessing/DataProcessingTrait.php
Classes/DataProcessing/FilesProcessor.php
Classes/DataProcessing/GalleryProcessor.php
Classes/DataProcessing/MenuProcessor.php
Configuration/TypoScript/ContentElement/MenuAbstract.typoscript
Configuration/TypoScript/ContentElement/MenuCategorizedPages.typoscript
Configuration/TypoScript/ContentElement/MenuRecentlyUpdated.typoscript
Configuration/TypoScript/ContentElement/MenuRelatedPages.typoscript
Configuration/TypoScript/ContentElement/MenuSection.typoscript
Configuration/TypoScript/ContentElement/MenuSectionPages.typoscript
Configuration/TypoScript/ContentElement/MenuSitemap.typoscript
Configuration/TypoScript/ContentElement/MenuSitemapPages.typoscript

[#112] Allow to append "data" by processingConfiguration flag

---

Classes/ContentObject/JsonContentObject.php
Classes/ContentObject/JsonDecoder.php
Classes/ContentObject/JsonDecoderInterface.php
Tests/Unit/ContentObject/JsonDecoderTest.php

Better checks for decoding json values, small code refactor

---

.github/workflows/ci.yaml
composer.json

[TASK] Add json lint #125
Resolves #125

[TASK] add composer json lint and run it as github action

---

Classes/DataProcessing/GalleryProcessor.php
Classes/Utility/FileUtility.php

[BUGFIX] fix gallery bugs

---

Classes/ContentObject/JsonContentObject.php
Classes/Json/JsonDecoder.php
Classes/Json/JsonDecoderInterface.php
Classes/Json/JsonEncoder.php
Classes/Json/JsonEncoderException.php
Classes/Json/JsonEncoderInterface.php
Configuration/Services.yaml
Tests/Unit/Json/JsonDecoderTest.php

[FEATURE] introduce json encoder & Services.yaml

---

Classes/DataProcessing/DataProcessingTrait.php
Classes/DataProcessing/FilesProcessor.php

add new flags to processingConfiguration:
- **returnFlattenObject** (allow to return object instead of array in case just one file/image/video)
- **autogenerate.retina2x** (generates retina version of base image file)
- **autogenerate.lqip** (generates low quality image placeholder of base image file)

[FEATURE] new FilesProcessor flags

---

Classes/DataProcessing/FilesProcessor.php

Allow return null if returnFlattenObject flag is set, it's better for frontend devs

[FEATURE] allow null if file is not processed

---

Classes/ContentObject/JsonContentObject.php

[FEATURE] allow return null if result of data processing is empty

---

Classes/ContentObject/BooleanContentObject.php
Classes/ContentObject/IntegerContentObject.php
Classes/ContentObject/JsonContentObject.php
README.md
ext_localconf.php

In order to provide better API for frontend devs in JSON response.

[FEATURE] INT & BOOL content object for use in JSON content object

---

Classes/DataProcessing/FlexFormProcessor.php

Fixes FlexFormProcessor.
In case of flexform data are already parsed/processed into an array (eg. gridelements) continue in processor flow.

[BUGFIX] FlexFormProcessor

---

Classes/ViewHelpers/Format/Json/DecodeViewHelper.php

Fix use cases of helper when using helper with argument in fluid template (without it throws exception)

[BUGFIX] add missing argument initialization

---

Classes/DataProcessing/DatabaseQueryProcessor.php

fix incorrect class in example code block

---

Documentation/Configuration/Index.rst
Documentation/Developer/Index.rst

First draft of documentation with available options & possibilities

ext:form integration documentation

---

Classes/Hooks/TypolinkHook.php

fixes exception in "redirects tab" in TYPO3 v10.4.9

[BUGFIX] add check for TSFE in TypolinkHook

---

Classes/Form/Decorator/AbstractFormDefinitionDecorator.php
Classes/Form/Translator.php
Configuration/TypoScript/Configuration/Form.typoscript

Add support for grouping of form elements via fieldsets

---

Classes/DataProcessing/FilesProcessor.php
Classes/DataProcessing/GalleryProcessor.php
Classes/Utility/FileUtility.php

by setting optional flags like in FilesProcessor

[FEATURE] allow to (auto) generate retina/lqip images for galleries of images

---

Classes/Form/Translator.php
Classes/XClass/Controller/FormFrontendController.php

- fix translation of nested elements
- fix generation of fieldnames for fieldset containers
- fix replacing of custom options in nested scenario

form support bug fixes

---

README.md

Add missing bracets and streamline indention in code examples. Also replace quotes in php code example.

[TASK] Cleanup typoscript snippets in README

---

Classes/Utility/FrontendBaseUtility.php
Classes/XClass/ResourceLocalDriver.php
ext_localconf.php

This feature allows to configure local file driver
to serve files via same domain and customizable per site/env

[FEATURE] Add frontendFileApi option in site configuration

---

Classes/Utility/FrontendBaseUtility.php
Classes/XClass/ResourceLocalDriver.php

- simplify method override in ResourceLocalDriver

[FIX] fix return type in FrontendBaseUtility

---

Classes/XClass/Routing/PageRouter.php
Classes/XClass/Typolink/PageLinkBuilder.php
ext_localconf.php

resolves #130
original work by @lukaszuznanski

[FEATURE] Add cross-domain headless links

---

.php_cs.dist
Classes/Service/PaginationService.php
Classes/ViewHelpers/Iterator/ExplodeViewHelper.php

[TASK] enable PSR-12 support in PHP-CS-Fixer

---

Classes/XClass/ResourceLocalDriver.php

when overriding proxy path to files

[BUGFIX] make sure TYPO3_REQUEST exist and is proper type

---

Classes/Hooks/TypolinkHook.php

- cs cleanup
- minor optimizations
- resolves #234

[BUGFIX] better handling external type page of typolink

---

README.md
UPGRADE.md

- add link to documentation, resolves #241

[TASK] update readme with feature flags

---

ext_localconf.php

- provide common namespace
- shorter names

[TASK] cleanup feature flags

---

Classes/Middleware/ShortcutAndMountPointRedirect.php
Configuration/RequestMiddlewares.php
README.md

- add new feature flag for handling redirects
- add & replace existing Shortcut middleware with headless one
- redirect should be handled by frontend app instead of TYPO3

[TASK] introduce headless.redirectMiddlewares flag

---

Classes/Middleware/ShortcutAndMountPointRedirect.php

[TASK] add check for mixed fluid/headless configuration

---

Classes/Middleware/RedirectHandler.php

- links should be relative (avoid reloading of frontend app)

[TASK] fix redirecting in same domain

---

Classes/Middleware/RedirectHandler.php

- links should be relative (avoid reloading of frontend app)

[TASK] proper fix for redirecting in same domain

---

Tests/Functional/ContentTypes/MenuSubpagesElementTest.php
Tests/Functional/Fixtures/content.xml

Basic test for Menu Subpages Element checking
basic information.
Releases: master

[TASK] Functional test for the Menu Subpages Element

---

Classes/Middleware/RedirectHandler.php

correctly handles target link in ext:redirect like "/test-target-url"

[BUGFIX] add support for "unknown type" in redirect handler

---

Tests/Functional/ContentTypes/MenuSitemapElementTest.php
Tests/Functional/Fixtures/content.xml

Basic test for Menu Sitemap Element checking basic information.

[TASK] Functional test for the Menu Sitemap Element

---

Tests/Functional/ContentTypes/MenuPagesElementTest.php
Tests/Functional/Fixtures/content.xml

Basic test for Menu Pages Element checking basic information.

[TASK] Functional test for the Menu Pages Element 

---

Tests/Functional/ContentTypes/MenuSectionElementTest.php
Tests/Functional/Fixtures/content.xml

Basic test for Menu Section Element checking basic information.

[TASK] Functional test for the Menu Section Element

---

Tests/Functional/ContentTypes/MenuCategorizedContentElementTest.php
Tests/Functional/Fixtures/content.xml

Basic test for Menu Categorized Content Element checking basic information. @

[TASK] Functional test for the Menu Categorized Content Element

---

Tests/Functional/ContentTypes/MenuCategorizedPagesElementTest.php
Tests/Functional/Fixtures/content.xml
Tests/Functional/Fixtures/pages.xml
Tests/Functional/PageTypes/StructureTest.php

Basic test for Menu Categorized Pages Element checking basic information.

[TASK] Functional test for the Menu Categorized Pages Element

---

Tests/Functional/ContentTypes/MenuSitemapSelectedPagesElementTest.php
Tests/Functional/Fixtures/content.xml
Tests/Functional/Fixtures/pages.xml
Tests/Functional/PageTypes/StructureTest.php

Basic test for Menu Sitemap Selected Pages Element checking basic information.

[TASK] Functional test for the Menu Sitemap Selected Pages Element

---

Tests/Functional/ContentTypes/MenuRecentlyUpdatedPagesElementTest.php
Tests/Functional/Fixtures/content.xml

Basic test for Menu Recently Updated Pages Element checking basic information.

[TASK] Functional test for the Menu Recently Updated Pages Element

---

Tests/Functional/ContentTypes/MenuRelatedPagesElementTest.php
Tests/Functional/Fixtures/content.xml
Tests/Functional/Fixtures/pages.xml
Tests/Functional/PageTypes/StructureTest.php

Basic test for Menu Related Pages Element checking basic information.

[TASK] Functional test for the Menu Related Pages Element

---

Classes/XClass/Domain/Model/FormDefinition.php
Configuration/Services.php
ext_localconf.php

[FEATURE] add support for ext:form in TYPO3 v9.5

---

Classes/Seo/XmlSitemap/XmlSitemapRenderer.php

Patch resolves issue when proxied sitemap in frontend can not find xls template.

[BUGFIX] Fix path for xsl template for sitemaps

---

Classes/Form/Finisher/JsonRedirectFinisher.php
Classes/XClass/Controller/FormFrontendController.php
Configuration/Services.php

- fix method definitions for v11
- fix handling instances without installed forms
- first batch of cleanup for PHP 7.4 & BC changes
- improve JsonRedirectFinisher

[TASK][v11] Improved forms support for v11

---

Classes/Seo/XmlSitemap/XmlSitemapRenderer.php

[BUGFIX] Remove trailing slash from hostname to prevent double slashes

---

Classes/DataProcessing/RootSiteProcessing/DomainSchema.php
Classes/DataProcessing/RootSiteProcessing/SiteProvider.php
Configuration/TypoScript/Configuration/Domains.typoscript
UPGRADE.md

- add additional check for listing domains only marked as headless
- code cleanup

[TASK] migrate headless_domains to endpoint ?type=835

---

Classes/Json/JsonEncoder.php
Tests/Unit/Json/JsonDecoderTest.php
Tests/Unit/Json/JsonEncoderTest.php

- fix response on Exception
- add resetSingletonInstances for Json(Encoder|Decoder) tests

[TASK] add test for JsonEncoder

---

Classes/Utility/FileUtility.php
Tests/Unit/Utility/FileUtilityTest.php

- as processFile uses processImageFile method for images all the public methods are in some way tested
- make FileUtility testable

Add tests for getAbsoluteUrl and processFile methods of FileUtility

---

Classes/Middleware/ElementBodyResponseMiddleware.php
Documentation/Configuration/Index.rst

- add ability to search for nested elements
- fix issue with cached content

[TASK] Element body middleware improvements

---

Classes/ContentObject/BooleanContentObject.php
Classes/ContentObject/FloatContentObject.php
Classes/ContentObject/IntegerContentObject.php
Classes/ContentObject/JsonContentObject.php
README.md
ext_localconf.php

Resolve https://github.com/TYPO3-Initiatives/headless/issues/381 and add a new FLOAT cObject to support float values in JSON.

[FEATURE] Add FLOAT cObject for JSON rendering

---

Classes/Middleware/ShortcutAndMountPointRedirect.php
Classes/Middleware/UserIntMiddleware.php
Configuration/TypoScript/2.x/Helper/ParseFunc.typoscript
Configuration/TypoScript/ContentElement/ParseFunc.typoscript
ext_localconf.php

Resolve 3 deprecations (single commit / deprecations)

[BUGFIX] Resolve deprecations in v11 (for v12)

---

Classes/ContentObject/FloatContentObject.php
Tests/Unit/ContentObject/FloatContentObjectTest.php

[TASK] Add tests for FLOAT ContentObject

---

Classes/Form/Translator.php
Tests/Unit/Form/Decorator/AbstractFormDefinitionDecoratorTest.php
Tests/Unit/Form/Decorator/FormDefinitionDecoratorTest.php
Tests/Unit/Form/TranslatorTest.php
composer.json

- small refactor for translator class

[TASK] add tests for form's components

---

Classes/ContentObject/JsonContentContentObject.php

- `merge` option allows to merge two CONTENT_JSON calls into one dataset (useful for using slides)
- `doNotGroupByColPos` allows not to group elements, but return flat array of elements
- resolves #212

[FEATURE] add `merge` & `doNotGroupByColPos` to CONTENT_JSON

---

README.md

just replace the links to nuxt-typo3 repo and docs

Update nuxt-typo3 links

---

Classes/ContentObject/JsonContentContentObject.php

[BUGFIX] do not change type on empty content

---

Classes/XClass/Typolink/PageLinkBuilder.php

[BUGFIX] fix warnings on PHP8 in PageLinkBuilder

---

Tests/Functional/ContentTypes/BaseContentTypeTest.php
Tests/Functional/ContentTypes/BasicListElementTest.php
Tests/Functional/ContentTypes/BulletsElementTest.php
Tests/Functional/ContentTypes/HeaderElementTest.php
Tests/Functional/ContentTypes/HtmlElementTest.php
Tests/Functional/ContentTypes/ShortcutElementTest.php
Tests/Functional/ContentTypes/TableElementTest.php
Tests/Functional/ContentTypes/TextElementTest.php
Tests/Functional/ContentTypes/TextMediaElementTest.php
Tests/Functional/ContentTypes/TextpicElementTest.php
Tests/Functional/Fixtures/content.xml
Tests/Functional/Fixtures/pages.xml

There is no 5th parameter in parameter value https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/Functions/Typolink.html#parameter
This is related to this change https://github.com/typo3/typo3/commit/e16fd7cba6

[BUGFIX] Fix functional tests due to typolink change

---

Configuration/TypoScript/2.x/ContentElement/Form.typoscript
Configuration/TypoScript/2.x/Helper/ContentElementWithHeader.typoscript
Configuration/TypoScript/2.x/Helper/Page.typoscript

[BUGFIX] fix BC response (2.x)

---

Configuration/TypoScript/Configuration/InitialDataConfiguration.typoscript
Configuration/TypoScript/Configuration/Languages.typoscript
Configuration/TypoScript/Configuration/PageConfiguration.typoscript

[BUGFIX] restore language node in page response

---

Classes/ContentObject/JsonContentContentObject.php

[BUGFIX] fix notice & allow array in when not grouping

---

Classes/Middleware/RedirectHandler.php

[BUGFIX] simplify RedirectHandler

---

Classes/Hooks/PreviewUrlHook.php
Classes/XClass/Controller/PreviewController.php
Documentation/Configuration/Index.rst
ext_localconf.php

This PR adds support for workspaces preview. When you set feature flag and workspaces extension is enabled and you are using frontend urls, then you can see your frontend page in preview properly.
@kitzberger please take a look.

[FEATURE] Add workspaces preview support

---

Classes/DataProcessing/FilesProcessor.php

[BUGFIX] add check if crop property is null

---

Classes/ContentObject/JsonContentContentObject.php

[FEATURE] add support for slides in CONTENT_JSON

---

Classes/XClass/Preview/PreviewUriBuilder.php
ext_localconf.php

[TASK] Rewrite tokenized preview URLs as well

---

Classes/Resource/Rendering/AudioTagRenderer.php
Classes/Resource/Rendering/VideoTagRenderer.php
Classes/Resource/Rendering/VimeoRenderer.php
Classes/Resource/Rendering/YouTubeRenderer.php

- remove dead code
- fix warnings on PHP 8.1
- resolves #502

[BUGFIX] fix warnings tag renderers

---

Configuration/TypoScript/2.x/ContentElement/Default.typoscript
Configuration/TypoScript/ContentElement/Default.typoscript
composer.json

- bump typoscript linter to v3
- cleanup composer.json

[TASK] composer.json cleanup & update TS linter

---

composer.json

[TASK] fix tests 2.x

---

Classes/Middleware/CookieDomainPerSite.php
Configuration/RequestMiddlewares.php
Configuration/SiteConfiguration/Overrides/site.php
Configuration/SiteConfiguration/Overrides/site_base_variant.php

[FEATURE] cookie domain per site

---

Classes/XClass/Typolink/PageLinkBuilder.php

[BUGFIX] allow to handle frontendBase without variant

---

Classes/DataProcessing/FilesProcessor.php
Classes/DataProcessing/GalleryProcessor.php
Classes/Utility/FileUtility.php
Configuration/TypoScript/ContentElement/Image.typoscript
Configuration/TypoScript/ContentElement/Textmedia.typoscript
Configuration/TypoScript/ContentElement/Textpic.typoscript

[BUGFIX] match handling of gallery processing with core

---

.github/workflows/ci.yaml
.github/workflows/codecoverage.yml
Classes/ContentObject/JsonContentContentObject.php
Classes/ContentObject/JsonContentObject.php
Classes/DataProcessing/MenuProcessor.php
Classes/ViewHelpers/Form/RegisterFieldViewHelper.php
Classes/ViewHelpers/LoginFormViewHelper.php
Configuration/Services.php
composer.json
ext_localconf.php

- first batch of fixes for v12
- new way of registering of CO
resolves #493, resolves #501

[TASK] add support v12

---

Classes/XClass/Controller/LoginController.php

make sure headless extension is enabled before overriding

[BUGFIX] Fix regression for mixed instance with felogin

---

Classes/Utility/UrlUtility.php
Tests/Unit/Utility/UrlUtilityTest.php

[FEATURE] Add possibility to replace FE domains for language variants

---

Classes/Event/EnrichFileDataEvent.php
Classes/Utility/FileUtility.php
Tests/Unit/Event/EnrichFileDataEventTest.php

Add original file reference before any of resource processing in order to address edge cases with custom properties. Resolves: #557

[FEATURE] Improve EnrichFileDataEvent

---

Classes/Resource/Rendering/AudioTagRenderer.php
Classes/Resource/Rendering/VideoTagRenderer.php
Classes/Resource/Rendering/VimeoRenderer.php
Classes/Resource/Rendering/YouTubeRenderer.php

[TASK] Remove not used flag in v12

---

Classes/DataProcessing/FilesProcessor.php

[BUGFIX] Fix issue with cropped images in gallery processing

---

Classes/Utility/UrlUtility.php
Tests/Unit/Utility/UrlUtilityTest.php

Hardening replacing frontend domains for edge case configurations.

[BUGFIX] Fix edge cases with resolving frontend domains

---

Classes/Event/Listener/AfterLinkIsGeneratedListener.php
Tests/Unit/Event/Listener/AfterLinkIsGeneratedListenerTest.php
Tests/Unit/Event/Listener/AfterPagePreviewUriGeneratedListenerTest.php

[BUGFIX] Fix issues with handling typolinks

---

Classes/XClass/Controller/FormFrontendController.php

Provides more flexibility
[FEATURE] Pass FormRuntime to CustomOptions handler Provides more flexibility

[FEATURE] Pass FormRuntime to CustomOptions handler

---

Configuration/Services.php

[BUGFIX] Properly wire services if cms-forms is not installed

---

Classes/DataProcessing/GalleryProcessor.php
Classes/Event/Listener/LoginConfirmedEventListener.php
Classes/ViewHelpers/LoginFormViewHelper.php
Classes/XClass/Controller/LoginController.php
Configuration/Services.php
Resources/Private/FeLogin/Templates/Login/Login.html

Required update of nuxt-typo3 with support of passing cookies from BE via SSR

[BUGFIX] Fix issues with login

---

Classes/Event/Listener/AfterCacheableContentIsGeneratedListener.php
Classes/Event/Listener/AfterLinkIsGeneratedListener.php
Classes/Event/Listener/AfterPagePreviewUriGeneratedListener.php
Classes/Form/Decorator/FormDefinitionDecorator.php
Classes/ViewHelpers/DomainViewHelper.php
Tests/Unit/ContentObject/DataProcessingExample.php
Tests/Unit/ContentObject/EmptyDataProcessingExample.php
Tests/Unit/DataProcessing/RootSiteProcessing/TestSiteProvider.php
composer.json

Also switch to main branch to avoid deprecations

[BUGFIX] Fixes for php-cs-fixer, also fix files

---

Classes/Event/Listener/AfterPagePreviewUriGeneratedListener.php
Tests/Unit/Event/Listener/AfterPagePreviewUriGeneratedListenerTest.php

[BUGFIX] Fix generating preview URL in BE

---

Classes/Utility/FileUtility.php
Documentation/Developer/Images.rst
Documentation/Index.rst
README.md

Documentation of image processing

---

Documentation/Developer/Index.rst

I (once again) had to look into the PHP code in order to understand what JSON is capable of. So I've added a new section to the documentation.

[DOCS] Mention properties of JSON

---

Classes/DataProcessing/DataProcessingTrait.php
Tests/Unit/Form/TranslatorTest.php

[BUGFIX] Fix PHP warning if `as` is not set

---

Classes/Form/Decorator/AbstractFormDefinitionDecorator.php
Classes/Form/Translator.php
Tests/Unit/ContentObject/JsonContentObjectTest.php
Tests/Unit/Form/TranslatorTest.php

- add customMessage field to handle custom message via FormEditor
Resolves: #711 #690

[BUGFIX] Address issues with recursion

---

Classes/Form/Decorator/AbstractFormDefinitionDecorator.php
Classes/Form/Translator.php
Tests/Unit/Form/TranslatorTest.php

[BUGFIX] Fix forms issues with recursion

---

Classes/Utility/FileUtility.php

[BUGFIX] Better normalize processing instructions

---

Classes/DataProcessing/FlexFormProcessor.php

[BUGFIX] Prevent undefined array key warning in FlexFormProcessor

---

Configuration/Services.php

Fix regression on ext:form handling on v12

[BUGFIX] Make Translator service public

---

.github/workflows/codecoverage.yml
Classes/XClass/Controller/PreviewControllerV12.php
Classes/XClass/Preview/PreviewUriBuilder.php
Configuration/Services.php
composer.json

[BUGFIX] Fix issues with >= v13.4.16
